# Render: PostgreSQL gerenciado pelo Render
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require&pgbouncer=true
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
